### ISSUE TITLE
function problem in template (object named as existed function)

### ISSUE THREAD

**Issue by nagydaniel** [Rapporter/pander#53]
```
<!--head
meta:
  title: ANOVA Template
  author: Aleksandar Blagotić, Dániel Nagy
  description: An ANOVA report with table of descriptives, diagnostic tests and ANOVA-specific
    statistics.
  email: ~
  packages: nortest
  example:
  - 'rapport("anova", ius2008, resp = "leisure", fac = "gender")  # one-way'
  - 'rapport("anova", ius2008, resp = "leisure", fac = c("gender", "partner")) # two-way'
inputs:
- name: test
  label: test
  description: test
  class: character
  value: ~
  required: yes
  standalone: yes
- name: noneed
  label: test
  description: test
  class: numeric
  length:
    min: 1
    max: 2
  required: yes
  standalone: no
head-->

<% for (i in 1:3) { %>
<%= signif <- paste(pander.return(lapply(1:i, function(i) paste0(p(c(rownames(test)[i])), ' (', round(test[i], 3), ')'))), collapse = '\n')
signif
%>
<% } %>
```
